stages:
  - test
  - build
  - deploy

test_python:
  stage: test
  tags:
    - runner1
  script:
    - docker run --rm -v "$CI_PROJECT_DIR/Python":/app:ro -w /app python:3.9-slim sh -c "pip install --no-cache-dir --prefix=/tmp/pip-temp -r requirements.txt && PYTHONPATH=/tmp/pip-temp/lib/python3.9/site-packages PYTHONDONTWRITEBYTECODE=1 python test_app.py"

test_rust:
  stage: test
  tags:
    - runner1
  script:
    - docker run --rm -v "$CI_PROJECT_DIR/Rust":/app:ro -w /app rust:1.88 sh -c "CARGO_TARGET_DIR=/tmp/target cargo test"

build_python:
  stage: build
  tags:
    - runner1
  script:
    - docker build -t microservices_python_app ./Python

build_rust:
  stage: build
  tags:
    - runner1
  script:
    - docker build -t microservices_rust_app ./Rust

deploy:
  stage: deploy
  tags:
    - runner1
  script:
    # اگر می‌خواهی شبکه و volume هم پاک شود:
    - docker-compose down || true
    - docker-compose up -d