```yaml
stages:
  - test
  - build
  - deploy

# -------------------------
# Test: Python Flask (local execution)
# -------------------------
test_python:
  stage: test
  tags:
    - runner1
  script:
    - pip install --no-cache-dir -r Python/requirements.txt
    - python3 Python/test_app.py

# -------------------------
# Test: Rust Actix (local execution)
# -------------------------
test_rust:
  stage: test
  tags:
    - runner1
  script:
    - cd Rust
    - cargo test

# -------------------------
# Build: Python Image
# -------------------------
build_python:
  stage: build
  tags:
    - runner1
  script:
    - docker build -t microservices_python_app ./Python

# -------------------------
# Build: Rust Image
# -------------------------
build_rust:
  stage: build
  tags:
    - runner1
  script:
    - docker build -t microservices_rust_app ./Rust

# -------------------------
# Deploy: Docker Compose
# -------------------------
deploy:
  stage: deploy
  tags:
    - runner1
  script:
    - docker-compose up -d
```
