version: "3.8"

services:
  python_app:
    build:
      context: ./Python
      dockerfile: Dockerfile
    container_name: flask_hello
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"      # هر فایل لاگ تا 5 مگابایت
        max-file: "3"       # حداکثر ۳ فایل چرخشی

  rust_app:
    build:
      context: ./Rust
      dockerfile: Dockerfile
    container_name: actix_hello
    ports:
      - "8080:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"