version: "3.8"

services:
  # -------------------------
  # اپلیکیشن‌ها
  # -------------------------
  python_app:
    image: mh1-python_app
    container_name: flask_hello
    ports:
      - "5000:5000"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  rust_app:
    image: mh1-rust_app
    container_name: actix_hello
    ports:
      - "8088:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
