version: "3.8"

services:
  # -------------------------
  # Metrics & Dashboard stack
  # -------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    network_mode: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev)($|/)"'
    restart: unless-stopped

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    network_mode: host
    restart: unless-stopped

  # -------------------------
  # Loki Logging Stack
  # -------------------------
  loki:
    image: grafana/loki:latest
    container_name: loki
    network_mode: host # Use host network mode
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      # Optional: if you have a custom Loki config file
      # - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki # Persist Loki data
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    network_mode: host # Use host network mode
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml:ro # Promtail config file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Docker log files
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for metadata
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    depends_on:
      - loki # Ensure Loki starts before Promtail

volumes:
  grafana_data: # Existing Grafana volume
  loki_data: # New volume for Loki data persistence
