version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - /home/mehdi/Projects/mh1/monitoring/loki-config.yml:/etc/loki/config.yml:ro
      - /home/mehdi/Projects/mh1/monitoring/loki-wal:/wal
      - /home/mehdi/Projects/mh1/monitoring/loki-data:/tmp/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /etc/hostname:/etc/hostname
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /home/mehdi/Projects/mh1/monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
