# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']    # cAdvisor در host network روی 8080

  - job_name: 'python_app'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'rust_app'
    static_configs:
      - targets: ['localhost:8088']    # Rust روی پورت جدید 8088
