[package]
name = "actix_hello"       # حتما این نام را با نام پوشه پروژه ات هماهنگ کن
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
actix-rt = "2"
